# Generated by Django 5.1.4 on 2025-01-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='CategoryID',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
