# Generated by Django 5.1.4 on 2025-01-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_shoe_categoryid_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image_url',
            field=models.ImageField(upload_to='shoes/'),
        ),
    ]
