# Generated by Django 5.1.4 on 2025-01-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_shoe_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
